# compose.yml
services:
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:8.6.1
    ports:
      - "6379:6379"
