# config/deploy.portal.yml
service: ehr-portal

image: scarver2/ehr-portal

builder:
  arch: amd64
  context: apps/ehr-portal

registry:
  server: docker.io
  username: scarver2

proxy:
  ssl: true
  host: ehr.stancarver.com
  app_port: 3000
  healthcheck:
    path: /api/up

servers:
  web:
    - 45.76.237.124

ssh:
  user: deploy

