# config/deploy.api.yml
service: ehr-api

image: ghcr.io/scarver2/ehr-api

builder:
  remote: ssh://deploy@45.76.237.124
  arch: amd64
  context: .
  dockerfile: apps/ehr-api/Dockerfile

registry:
  server: ghcr.io
  username: scarver2
  password:
    - GITHUB_TOKEN

proxy:
  ssl: true
  host: api.ehr.stancarver.com
  app_port: 3000
  healthcheck:
    path: /up

servers:
  web:
    - 45.76.237.124
  worker:
    hosts:
      - 45.76.237.124
    cmd: bundle exec sidekiq -C config/sidekiq.yml

ssh:
  user: deploy

env:
  secret:
    - SECRET_KEY_BASE
    - DB_USER
    - DB_PASSWORD
    - HONEYBADGER_API_KEY
    - REDIS_URL

accessories:
  postgres:
    image: postgres:18
    host: 45.76.237.124
    port: 5432
    env:
      clear:
        POSTGRES_DB: ehr_api_production
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    volumes:
      - ehr_api_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    host: 45.76.237.124
    port: 6379
    volumes:
      - ehr_api_redis_data:/data
