# config/deploy.portal.yml
service: ehr-portal

image: scarver2/ehr-portal

builder:
  remote: ssh://deploy@45.76.237.124
  arch: amd64
  context: apps/ehr-portal

env:
  clear:
    NEXT_PUBLIC_API_URL: https://api.ehr.stancarver.com
  secret:
    - NEXT_PUBLIC_HONEYBADGER_API_KEY

proxy:
  ssl: true
  host: ehr.stancarver.com
  app_port: 3000
  healthcheck:
    path: /api/up

servers:
  web:
    - 45.76.237.124

ssh:
  user: deploy

