# config/deploy.api.yml
service: ehr-api

image: scarver2/ehr-api

builder:
  remote: ssh://deploy@45.76.237.124
  arch: amd64
  cache:
    type: registry
    options: mode=max
  context: apps/ehr-api
  dockerfile: apps/ehr-api/Dockerfile
  args:
    GIT_SHA: <%= `git rev-parse --short HEAD`.strip %>
    GIT_BRANCH: <%= `git rev-parse --abbrev-ref HEAD`.strip %>

env:
  secret:
    - SECRET_KEY_BASE
    - DB_USER
    - DB_PASSWORD
  clear:
    DB_HOST: ehr-api-postgres
    DB_PORT: 5432
    DB_NAME: ehr_api_production

proxy:
  ssl: true
  host: api.ehr.stancarver.com
  app_port: 3000
  # drain_timeout: 30
  healthcheck:
    path: /api/up

registry:
  server: ghcr.io
  username: scarver2
  password:
    - GITHUB_TOKEN

servers:
  # db:
  #   - 45.76.237.124
  web:
    - 45.76.237.124

ssh:
  user: deploy

accessories:
  postgres:
    image: postgres:18
    host: 45.76.237.124
    port: "5432:5432"
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_DB: ehr_api_production
    directories:
      - data:/var/lib/postgresql
