# config/deploy.portal.yml
service: ehr-portal

image: scarver2/ehr-portal

builder:
  arch: amd64
  cache:
    type: registry
    options: mode=max
  context: apps/ehr-portal
  dockerfile: apps/ehr-portal/Dockerfile

env:
  clear:
    NEXT_PUBLIC_API_URL: https://api.ehr.stancarver.com

proxy:
  ssl: true
  host: ehr.stancarver.com
  app_port: 3000
  healthcheck:
    path: /api/up

registry:
  server: ghcr.io
  username: scarver2
  password:
    - GITHUB_TOKEN

servers:
  web:
    - 45.76.237.124

ssh:
  user: deploy
