# apps/ehr-api/config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "scarver2") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: ehr_api_development

test:
  <<: *default
  database: ehr_api_test

production:
  <<: *default
  database: ehr_api_production
