source "https://rubygems.org"

# https://rubyonrails.org
gem "rails", "~> 8.1.2"

# https://github.com/ged/ruby-pg
gem "pg", "~> 1.1"

# https://puma.io
gem "puma", ">= 5.0"

# https://github.com/tzinfo/tzinfo-data
gem "tzinfo-data", platforms: %i[ windows jruby ]

# https://github.com/cyu/rack-cors
gem "rack-cors"

group :development do
  # https://github.com/soutaro/steep
  gem "steep",             require: false

  # https://github.com/rmosolgo/graphiql-rails
  gem "graphiql-rails",    "~> 1.10"

  # https://github.com/BetterErrors/better_errors
  gem "better_errors",     "~> 2.10"

  # https://github.com/banister/binding_of_caller
  gem "binding_of_caller", "~> 2.0"

  # https://brakemanscanner.org
  gem "brakeman",          "~> 8.0",  require: false

  # https://github.com/guard/guard
  gem "guard",             "~> 2.18", require: false

  # https://github.com/guard/guard-bundler
  gem "guard-bundler",                require: false

  # https://github.com/guard/guard-rspec
  gem "guard-rspec",       "~> 4.7",  require: false

  # https://github.com/rubocop/guard-rubocop
  gem "guard-rubocop",     "~> 1.5",  require: false

  # https://github.com/janlelis/irbtools
  gem "irbtools"

  # https://github.com/onesupercoder/rack-livereload
  gem "rack-livereload",              require: false

  # https://miniprofiler.com
  gem "rack-mini-profiler",           require: false

  # https://github.com/tmm1/stackprof
  gem "stackprof",                    require: false

  # https://github.com/Springest/terminal-notifier-guard
  gem "terminal-notifier-guard", "~> 1.7", require: false
end

group :development, :test do
  # https://github.com/ruby/debug
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # https://github.com/amazing-print/amazing_print
  gem "amazing_print", "~> 2.0"

  # https://github.com/rspec/rspec-rails
  gem "rspec-rails", "~> 8.0"

  # https://github.com/rspec/rspec-its
  gem "rspec-its", "~> 2.0"

  # https://github.com/thoughtbot/factory_bot_rails
  gem "factory_bot_rails", "~> 6.5"

  # https://rubocop.org
  gem "rubocop", "~> 1.85"

  # https://github.com/rubocop/rubocop-capybara
  gem "rubocop-capybara", "~> 2.22"

  # https://github.com/rubocop/rubocop-factory_bot
  gem "rubocop-factory_bot", "~> 2.28"

  # https://github.com/rubocop/rubocop-rails
  gem "rubocop-rails", "~> 2.34"

  # https://github.com/rubocop/rubocop-performance
  gem "rubocop-performance", "~> 1.26"

  # https://github.com/DmitryTsepelev/rubocop-graphql
  gem "rubocop-graphql",     "~> 1.5"

  # https://github.com/rubocop/rubocop-rspec
  gem "rubocop-rspec",       "~> 3.9"

  # https://github.com/rubocop/rubocop-rspec_rails
  gem "rubocop-rspec_rails", "~> 2.31"
end

group :test do
  # https://github.com/simplecov-ruby/simplecov
  gem "simplecov", "~> 0.22.0"
end

# https://github.com/heartcombo/devise
gem "devise", "~> 5.0"

# https://github.com/faker-ruby/faker
gem "faker", "~> 3.6"

# https://graphql-ruby.org
gem "graphql", "~> 2.5"

# https://github.com/rails/solid_queue
gem "solid_queue", "~> 1.3"

# https://github.com/Shopify/bootsnap
gem "bootsnap", "~> 1.23", require: false

# https://activeadmin.info
gem "activeadmin", "~> 3.5"

# https://github.com/rails/propshaft
gem "propshaft", "~> 1.3"

# https://github.com/rails/dartsass-rails
gem "dartsass-rails", "~> 0.5"

# https://www.honeybadger.io
gem "honeybadger", "~> 6.0"
